<template>
  <div>
    <PageTitle title="Pools" />
    <v-card>
      <v-card-title>Pools Preparation</v-card-title>
      <v-data-table
        :headers="headers"
        :items="pools"
        item-key="name"
        group-by="generationSource.name"
        disable-sort
        hide-default-footer
      >
        <template #[`group.header`]="{ group, headers, toggle, isOpen }">
          <td :colspan="headers.length">
            <v-btn :ref="group" small icon @click="toggle">
              <v-icon v-if="isOpen">mdi-minus</v-icon>
              <v-icon v-else>mdi-plus</v-icon>
            </v-btn>
            <span class="ml-5 font-weight-bold">{{ group }}</span>
          </td>
        </template>
        <template #top>
          <v-toolbar flat>
            <v-spacer />
            <PoolForm />
          </v-toolbar>
        </template>
        <template #[`item.size`]="{ item }">
          <PoolCompetitorList :pool="item" />
        </template>
        <template #[`item.system`]="{ item }">
          <v-row no-gutters align="center">
            <v-col>
              <PoolSystemSelectBox :pool="item" />
            </v-col>
            <v-col>
              <PoolDrawView :pool="item" :system="item.system" />
            </v-col>
          </v-row>
        </template>
        <template #[`item.info`]="{ item }">
          <v-tooltip v-if="item.generated" bottom>
            <template #activator="{ on, attrs }">
              <v-icon v-bind="attrs" v-on="on">mdi-information</v-icon>
            </template>
            <span>This pool was generated by the category</span>
          </v-tooltip>
        </template>
        <template #[`item.actions`]="{ item }">
          <PoolForm :prefilled="item">
            <v-btn small @click="setReadyForSchedule(item)">
              Push to Schedule
            </v-btn>
          </PoolForm>
        </template>
      </v-data-table>
    </v-card>

    <v-data-table
      :headers="competitorsHeaders"
      :items="unassignedPeople"
      disable-sort
      hide-default-footer
    >
      <template #[`item.potential_pools`]="{ item }">
        <AssignToPool :competitor="item" />
      </template>
    </v-data-table>

    <v-card>
      <v-card-title>Pools Ready Scheduled</v-card-title>
      <v-data-table
        :headers="poolsReadyHeaders"
        :items="poolsReady"
        item-key="name"
        disable-sort
        hide-default-footer
      >
        <template #[`item.size`]="{ item }">
          <PoolCompetitorList :pool="item" :readonly="true" />
        </template>
        <template #[`item.actions`]="{ item }">
          <v-btn @click="setNotReadyForSchedule(item)"> Take back</v-btn>
        </template>
      </v-data-table>
    </v-card>
  </div>
</template>

<script lang="ts">
// FIXME: Should not need to initialize competitors Store here...
// Maybe move it into init of poolsStore?
import { Component, Vue } from 'vue-property-decorator';
import { DataTableHeader } from 'vuetify';
import { poolsStore, competitorsStore, alertStore } from '~/store';
import { Competitor, Pool } from '~/types/models';
import PageTitle from '~/components/common/PageTitle.vue';
import PoolForm from '~/components/PoolForm.vue';
import PoolCompetitorList from '~/components/PoolCompetitorList.vue';
import PoolSystemSelectBox from '~/components/PoolSystemSelectBox.vue';
import PoolDrawView from '~/components/PoolDrawView.vue';
import AssignToPool from '~/components/AssignToPool.vue';

@Component({
  components: { AssignToPool, PoolDrawView, PoolSystemSelectBox, PoolCompetitorList, PoolForm, PageTitle },
  layout: 'DashboardLayout',
})
export default class Pools extends Vue {
  private headers: DataTableHeader<Pool>[] = [
    { text: 'Pool', value: 'name' },
    { text: 'Size', value: 'size' },
    { text: 'System', value: 'system' },
    { text: 'Info', value: 'info' },
    { text: 'Status', value: 'status' },
    { text: 'Actions', value: 'actions' },
  ];

  private competitorsHeaders: DataTableHeader<Competitor>[] = [
    { text: 'Firstname', value: 'firstname' },
    { text: 'Lastname', value: 'lastname' },
    { text: 'Birthyear', value: 'birthyear' },
    { text: 'Weight', value: 'weightMeasured' },
    { text: 'Potential Pools', value: 'potential_pools' },
    { text: 'Actions', value: 'actions' },
  ]

  private poolsReadyHeaders: DataTableHeader<Pool>[] = [
    { text: 'Pool', value: 'name' },
    { text: 'Size', value: 'size' },
    { text: 'System', value: 'system' },
    { text: 'Actions', value: 'actions' },
  ]

  private get pools(): Pool[] {
    return poolsStore.pools;
  }

  private get poolsReady(): Pool[] {
    return poolsStore.poolsReady;
  }

  private get unassignedPeople(): Competitor[] {
    return competitorsStore.list;
  }

  private setReadyForSchedule(pool: Pool): void {
    poolsStore.ready(pool)
      .catch((err) => {
        alertStore.setError({ msg: err });
      });
  }

  private setNotReadyForSchedule(pool: Pool): void {
    poolsStore.notReady(pool);
  }

  public async fetch() {
    await competitorsStore.init();
    await poolsStore.init();
  }

  public async mounted() {
    await competitorsStore.init();
    await poolsStore.init();
  }
}
</script>
