<template>
  <div>
    <h1>Pools</h1>
    <v-row>
      <v-col>
        <v-card>
          <v-card-title>Pools Preparation</v-card-title>
          <v-data-table
            :headers="headers"
            :items="items"
            item-key="name"
            disable-sort
            hide-default-footer
          >
            <template v-slot:item.size="{ item }">
              <CompetitorList :pool="item" />
            </template>
            <template v-slot:item.system="{ item }">
              <v-row no-gutters align="center">
                <v-col>
                  <v-select :value="item.system" :items="systems"></v-select>
                </v-col>
                <v-col>
                  <DrawView :pool="item" :system="item.system" />
                </v-col>
              </v-row>
            </template>
            <template v-slot:item.info="{ item }">
              <v-tooltip v-if="item.generated" bottom>
                <template v-slot:activator="{ on, attrs }">
                  <v-icon v-bind="attrs" v-on="on"> mdi-information</v-icon>
                </template>
                <span>This pool was generated by the category</span>
              </v-tooltip>
            </template>
            <template v-slot:item.actions="{ item }">
              <v-btn @click="setReadyForSchedule(item)">
                Push to Schedule
              </v-btn>
            </template>
          </v-data-table>
        </v-card>
      </v-col>
      <v-col>
        <v-data-table
          :headers="competitors_headers"
          :items="unassigned_people"
          disable-sort
          hide-default-footer
        >
          <template v-slot:item.potential_pools="{ item }">
            <AssignToPool :competitor="item" />
          </template>
        </v-data-table>
      </v-col>
    </v-row>
    <v-card>
      <v-card-title>Pools Ready Scheduled </v-card-title>
      <v-data-table
        :headers="pools_ready_headers"
        :items="pools_ready_items"
        item-key="name"
        disable-sort
        hide-default-footer
      >
        >
        <template v-slot:item.size="{ item }">
          <CompetitorList :pool="item" :readonly="true" />
        </template>
        <template v-slot:item.actions="{ item }">
          <v-btn @click="setNotReadyForSchedule(item)"> Take back </v-btn>
        </template>
      </v-data-table>
    </v-card>
  </div>
</template>

<script>
import DrawView from '~/components/DrawView.vue'
export default {
  layout: 'DashboardLayout',
  components: { DrawView },
  data: () => ({
    systems: ['Round Robin', 'Bresil'],
    headers: [
      { text: 'Pool', value: 'name' },
      { text: 'Size', value: 'size' },
      { text: 'System', value: 'system' },
      { text: 'Info', value: 'info' },
      { text: 'Actions', value: 'actions' },
    ],
    competitors_headers: [
      { text: 'Firstname', value: 'firstname' },
      { text: 'Lastname', value: 'lastname' },
      { text: 'Weight', value: 'weight' },
      { text: 'Potential Pools', value: 'potential_pools' },
      { text: 'Actions', value: 'actions' },
    ],
    pools_ready_headers: [
      { text: 'Pool', value: 'name' },
      { text: 'Size', value: 'size' },
      { text: 'System', value: 'system' },
      { text: 'Actions', value: 'actions' },
    ],
  }),
  computed: {
    items() {
      return this.$store.state.pools.list.filter(
        (pool) => pool.status === 'not ready'
      )
    },
    pools_ready_items() {
      return this.$store.state.pools.list.filter(
        (pool) => pool.status === 'ready'
      )
    },
    unassigned_people() {
      return this.$store.state.competitors.list
    },
  },
  methods: {
    setReadyForSchedule(pool) {
      this.$store.commit('pools/ready', pool.id)
    },
    setNotReadyForSchedule(pool) {
      this.$store.commit('pools/notReady', pool.id)
    },
  },
}
</script>
